### ISSUE TITLE
Schema management

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#286]
- [x] Surface API
- [ ] SHACL schema for schema #363
- [ ] SHACL schema for resource
- [x] Authorization directives BlueBrain/nexus-admin#55
- [x] Project prefixmapping directive BlueBrain/nexus-admin#55
- [x] Routes
